FROM node:20

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN chmod +x start.sh

EXPOSE 4000

CMD ["./start.sh"]